workflows:
  ios-free:
    name: iOS Free Build (Simulator)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS simulator app
        script: |
          flutter build ios --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app
